### ISSUE TITLE
istio-pilot fails to process `ingress-relation-broken` event during charm remove

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#189]
`juju remove-application istio-pilot` will fail with the following debug-log:

```
Traceback (most recent call last):
  File "./src/charm.py", line 430, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 257, in handle_ingress
    del routes[(event.relation, event.app)]
KeyError: (<ops.model.Relation ingress:3>, None)
2023-03-13 18:56:53 ERROR juju.worker.uniter.operation runhook.go:140 hook "ingress-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
2023-03-13 18:56:53 INFO juju.worker.uniter resolver.go:145 awaiting error resolution for "relation-broken" hook
2023-03-13 18:58:39 INFO juju.worker.uniter resolver.go:145 awaiting error resolution for "relation-broken" hook
```

It appears that [this line](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/src/charm.py#L257) does not work correctly.  

I have not tested it, but this probably affects the ingress-relation-broken event independent of it being called during a remove-application

**Comment by ca-scribner** [comment]
Closed by #261

**Comment by ca-scribner** [comment]
I didn't hit this when working on #277, but @NohaIhab later hit it when following those steps for something unrelated.  I wonder if there's a race condition at play here?  Maybe if the other app is already gone, `event.app` will show `None` instead of the app name? 

We could try to fix this by skipping the `routes.pop` if `event.app is None`, but it isn't clear whether the data in the relation is actually gone at this point or not.

**Comment by ca-scribner** [comment]
[this issue](https://github.com/canonical/operator/issues/888) covers the same situation

**Comment by DnPlas** [comment]
The description of this issue originally pointed to a charm code that is no longer present, but from [this](https://github.com/canonical/istio-operators/issues/189#issuecomment-1591105345) other comment we can tell that the issue is very similar, in fact both of the logs show how the `ingress-relation-broken` ends in an error when the `event.app == None`. 

From what is described in https://github.com/canonical/operator/issues/888, we know that sometimes relation data is not emptied when relation-broken is emitted, thus we have to handle these cases to avoid from setting the unit into an unrecoverable state. Until the linked issue is fixed (or we are provided with a pattern to handle relation broken events in a proper way), we can just log the error and move on, relying on our multiple reconcile methods to remove the unwanted resources (from the departing app).

#291 should fix this issue.
