### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/istio-operators#244]
trying to deploy 1.7. Get

```
unit-istio-pilot-0: 19:11:23 ERROR unit.istio-pilot/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 669, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 436, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 866, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 118, in install
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./istioctl', 'install', '-y', '-s', 'profile=minimal', '-s', 'values.global.istioNamespace=kubeflow']' returned non-zero exit status 1.
```

we should not allow errors to leak. Rather go into loop and try again. Or identify the root cause why it failed and report to the user

**Comment by misohu** [comment]
This is no longer an issue.
