### ISSUE TITLE
`istio-pilot` goes to Error if the charms related via `ingress-auth` are not ready

### ISSUE THREAD

**Issue by orfeas-k** [canonical/istio-operators#336]
We **think** that `istio-pilot` goes to Error state with message `hook failed: "ingress-relation-changed"` when the charm related via `ingress-auth` is not ready yet. We 've noticed this while deploying CKF `1.7/edge` in an airgapped environment and `oidc-gatekeeper` [was in Blocked](https://github.com/canonical/oidc-gatekeeper-operator/blob/main/src/charm.py#L140-L143). It took some minutes to `istio-pilot` going to `active` after we 've configured `oidc-gatekeeper` (thus it went to active).

Logs from the unit
```
unit-istio-pilot-0: 13:33:55 ERROR unit.istio-pilot/0.juju-log ingress:16: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 983, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 246, in reconcile
    ingress_auth_data = self._get_ingress_auth_data(event)
  File "./src/charm.py", line 451, in _get_ingress_auth_data
    ingress_auth_data = list(ingress_auth_data.values())[0]
IndexError: list index out of range
unit-istio-pilot-0: 13:33:56 ERROR juju.worker.uniter.operation hook "ingress-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```
which means that it errored out [here](https://github.com/canonical/istio-operators/blob/track/1.16/charms/istio-pilot/src/charm.py#L451).

**Comment by kimwnasptd** [comment]
Bumped into this as well when playing around with the `1.7/stable` bundle. This seem to happen quite frequently, so we'll need to prioritize

**Comment by orfeas-k** [comment]
Closed by https://github.com/canonical/istio-operators/pull/342
