### ISSUE TITLE
istio-pilot charm goes in Error state with `hook failed: "gateway-info-relation-joined"`

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/istio-operators#346]
### Bug Description

After deploying from 1.7/stable bundle all Charms go to active state aside from `istio-pilot` which shows the error message `hook failed: "gateway-info-relation-joined"`

### To Reproduce

Follow instructions of https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow to do a clean installation of CKF 1.7

### Environment

Using the `1.7/stable` bundle and the `istio-pilot` charm is
* track **1.16/stable**
* revision **662**

### Relevant log output

```shell
2023-10-20T11:34:23.084Z [container-agent] 2023-10-20 11:34:23 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "relation-joined" hook
2023-10-20T11:39:23.105Z [container-agent] 2023-10-20 11:39:23 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "relation-joined" hook
2023-10-20T11:39:23.509Z [container-agent] 2023-10-20 11:39:23 WARNING juju-log gateway-info:17: 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
2023-10-20T11:39:23.513Z [container-agent] 2023-10-20 11:39:23 WARNING juju-log gateway-info:17: Invalid Grafana dashboards folder at /var/lib/juju/agents/unit-istio-pilot-0/charm/src/grafana_dashboards: directory does not exist
2023-10-20T11:39:23.646Z [container-agent] 2023-10-20 11:39:23 ERROR juju-log gateway-info:17: Uncaught exception while in charm code:
2023-10-20T11:39:23.646Z [container-agent] Traceback (most recent call last):
2023-10-20T11:39:23.646Z [container-agent]   File "./src/charm.py", line 983, in <module>
2023-10-20T11:39:23.646Z [container-agent]     main(Operator)
2023-10-20T11:39:23.646Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 441, in main
2023-10-20T11:39:23.646Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2023-10-20T11:39:23.646Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
2023-10-20T11:39:23.646Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2023-10-20T11:39:23.646Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 354, in emit
2023-10-20T11:39:23.646Z [container-agent]     framework._emit(event)
2023-10-20T11:39:23.646Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 830, in _emit
2023-10-20T11:39:23.646Z [container-agent]     self._reemit(event_path)
2023-10-20T11:39:23.646Z [container-agent]   File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 919, in _reemit
2023-10-20T11:39:23.646Z [container-agent]     custom_handler(event)
2023-10-20T11:39:23.646Z [container-agent]   File "./src/charm.py", line 246, in reconcile
2023-10-20T11:39:23.646Z [container-agent]     ingress_auth_data = self._get_ingress_auth_data(event)
2023-10-20T11:39:23.646Z [container-agent]   File "./src/charm.py", line 451, in _get_ingress_auth_data
2023-10-20T11:39:23.646Z [container-agent]     ingress_auth_data = list(ingress_auth_data.values())[0]
2023-10-20T11:39:23.646Z [container-agent] IndexError: list index out of range
2023-10-20T11:39:23.897Z [container-agent] 2023-10-20 11:39:23 ERROR juju.worker.uniter.operation runhook.go:153 hook "gateway-info-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

This seems to be the same underlying issue with https://github.com/canonical/istio-operators/issues/336 which would be solved by https://github.com/canonical/istio-operators/pull/342

**Comment by orfeas-k** [comment]
Closed by https://github.com/canonical/istio-operators/pull/342
