### ISSUE TITLE
Remove hook fails with not found error from k8s

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#95]
When removing istio-pilot, the remove hook fails with debug logs showing:
```
Traceback (most recent call last):
  File "./src/charm.py", line 168, in handle_ingress
    if not self._gateway_address:
  File "./src/charm.py", line 297, in _gateway_address
    svcs = self.lightkube_client.get(
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/client.py", line 108, in get
    return self._client.request("get", res=res, name=name, namespace=namespace)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 245, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: services "istio-ingressgateway-workload" not found
unit-istio-pilot-0: 13:27:42 ERROR unit.istio-pilot/0.juju-log ApiError: Could not get istio-ingressgateway-workload, deferring this event
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://10.152.183.1/api/v1/namespaces/kubeflow/services/istio-ingressgateway-workload'
For more information check: https://httpstatuses.com/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 168, in handle_ingress
    if not self._gateway_address:
  File "./src/charm.py", line 297, in _gateway_address
    svcs = self.lightkube_client.get(
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/client.py", line 108, in get
    return self._client.request("get", res=res, name=name, namespace=namespace)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 245, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: services "istio-ingressgateway-workload" not found
unit-istio-pilot-0: 13:27:43 ERROR unit.istio-pilot/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 304, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 106, in remove
    self._resource_handler.delete_manifest(
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/src/resources_handler.py", line 84, in delete_manifest
    for obj in codecs.load_all_yaml(manifest):
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/codecs.py", line 139, in load_all_yaml
    res.append(from_dict(obj, client=client))
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/lightkube/codecs.py", line 110, in from_dict
    if attr not in d:
TypeError: argument of type 'NoneType' is not iterable
```

It looks like it is trying to delete something that doesn't exist (maybe it was already deleted?)

**Comment by ca-scribner** [comment]
I think this is no longer valid.  There is a separate error that now blocks the `remove` hook.

**Comment by ca-scribner** [comment]
I believe #189 is now blocking removal, not this issue
